module.exports = {
  tokenAdmin:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXIiOiJSaWNhcmRvIiwiaWQiOiJlY2M2NDhiMC1kMzIxLTExZTktOTIwNS01NzI2ODNhYTU0Y2QiLCJub21lIjoiUmljYXJkbyBMZXJuZXIiLCJ0eXBlIjoiYWRtaW4ifSwiaWF0IjoxNjA4MzAyODQwLCJleHAiOjE2Mzk4Mzg4NDB9.ka2f7JN8pFE7aUdH4aWDBnpnP4uyfcAUQFLOIVd2ObA',
  company: {
    nome: 'Empresa',
    agencia: '1',
    banco: '1',
    cnpj: '',
    conta: '1',
    limiteGastoDiario: null,
    metodoAbastecimento: 'valorLitragem',
    saldo: null,
    telefone: '',
    tipoConta: 'pos',
    tickets: null,
  },
  gasStation: {
    agencia: '1',
    bairro: '1',
    banco: '1',
    cidade: '1',
    cnpj: '11111111111111111111',
    conta: '1',
    diesel: 100,
    etanol: 100,
    ganhoDiesel: 100,
    ganhoEtanol: 100,
    ganhoGasolina: 100,
    gasolina: 100,
    horarioAtendimentoFim: '22:00',
    horarioAtendimentoInicio: '06:00',
    latitude: '1',
    logradouro: '1',
    longitude: '1',
    bandeira: 'bandeira branca',
    categoria: 'veículo',
    nome: 'Posto',
    tipo: 'externo',
    aprovacao: 'manual',
    armazenamento: 'tanque',
    combustivel: 'gasolina',
  },

  companyAccount: {
    nome: 'Conta Frota',
    email: 'teste@gasola.com',
  },
  driver: {
    centroCusto: null,
    cpf: '123.456.897-98',
    matricula: '123',
    nome: 'Motorista',
    supervisor: null,
    perfil: 'motorista',
  },
  plate: {
    ano: 2020,
    fatorCo2: null,
    limiteGastoKmLitroMinimo: null,
    limiteGastoKmLitroMaximo: null,
    limiteAbastecimentoCombustivelNormal: null,
    limiteAbastecimentoCombustivelArla: null,
    marca: 'marca X',
    modelo: 'modelo Y',
  },
  settings: {
    valorVenda: 1,
    taxaGasola: 1,
    prazoPagamentoCliente: 12,
    prazoPagamentoGasola: 12,
    desconto: 1,
    visivel: true,
  },
  reportHeaders: {
    pageSize: 1,
    page: 1,
  },

  companyList: {
    priceLiters: {
      nome: 'Empresa por valor e litragem',
      agencia: '1',
      banco: '1',
      cnpj: '',
      conta: '1',
      limiteGastoDiario: null,
      metodoAbastecimento: 'valorLitragem',
      saldo: null,
      telefone: '',
      tipoConta: 'pos',
      tickets: null,
    },
    price: {
      nome: 'Empresa por valor',
      agencia: '1',
      banco: '1',
      cnpj: '',
      conta: '1',
      limiteGastoDiario: null,
      metodoAbastecimento: 'valor',
      saldo: null,
      telefone: '',
      tipoConta: 'pos',
      tickets: null,
    },
    liters: {
      nome: 'Empresa por litragem',
      agencia: '1',
      banco: '1',
      cnpj: '',
      conta: '1',
      limiteGastoDiario: null,
      metodoAbastecimento: 'litragem',
      saldo: null,
      telefone: '',
      tipoConta: 'pos',
      tickets: null,
    },
  },
  gasStationList: {
    vehicleExternalManual: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'veículo',
      nome: 'Posto veículo externo manual',
      tipo: 'externo',
      aprovacao: 'manual',
      armazenamento: null,
      combustivel: null,
    },
    vehicleExternalAutomatic: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'veículo',
      nome: 'Posto veículo externo automatico',
      tipo: 'externo',
      aprovacao: 'automatico',
      armazenamento: null,
      combustivel: null,
    },
    vehicleInternalManual: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'veículo',
      nome: 'Posto veículo interno manual',
      tipo: 'interno',
      aprovacao: 'manual',
      armazenamento: null,
      combustivel: null,
    },
    vehicleInternalAutomatic: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'veículo',
      nome: 'Posto veículo interno automatico',
      tipo: 'interno',
      aprovacao: 'automatico',
      armazenamento: null,
      combustivel: null,
    },
    forkliftExternalManual: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'empilhadeira',
      nome: 'Posto empilhadeira externo manual',
      tipo: 'externo',
      aprovacao: 'manual',
      armazenamento: null,
      combustivel: null,
    },
    forkliftExternalAutomatic: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'empilhadeira',
      nome: 'Posto empilhadeira externo automatico',
      tipo: 'externo',
      aprovacao: 'automatico',
      armazenamento: null,
      combustivel: null,
    },
    forkliftInternalManual: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'empilhadeira',
      nome: 'Posto empilhadeira interno manual',
      tipo: 'interno',
      aprovacao: 'manual',
      armazenamento: null,
      combustivel: null,
    },
    forkliftInternalAutomatic: {
      agencia: '1',
      bairro: '1',
      banco: '1',
      cidade: '1',
      cnpj: '11111111111111111111',
      conta: '1',
      horarioAtendimentoFim: '22:00',
      horarioAtendimentoInicio: '06:00',
      latitude: '1',
      logradouro: '1',
      longitude: '1',
      bandeira: 'bandeira branca',
      categoria: 'empilhadeira',
      nome: 'Posto empilhadeira interno automatico',
      tipo: 'interno',
      aprovacao: 'automatico',
      armazenamento: null,
      combustivel: null,
    },
  },
  userList: {
    centroCusto: '1',
    cpf: '111.111.111-11',
    matricula: '1',
    nome: 'fulano',
    senha: '1',
    supervisor: '1',
    usuario: 'fulano',
  },
  lockUserList: {
    driverAllPlatesAllGasUnlocked: {
      arla: true,
      centroCusto: '1',
      codigo: '24419482',
      cpf: '',
      dieselS10: true,
      dieselS500: true,
      etanol: true,
      gas: false,
      gasolina: true,
      gasolinaAditivada: true,
      limiteGastoAbastecimento: null,
      limiteGastoAbastecimentoFormatado: 'R$0.00',
      limiteGastoDiario: null,
      limiteGastoDiarioFormatado: 'R$0.00',
      limiteGastoMensal: null,
      limiteGastoMensalFormatado: 'R$0.00',
      matricula: '4',
      nome: 'fulano',
      origem: 'interno',
      perfil: 'motorista',
      permitePrecoDivergente: false,
      plate: null,
      plate_id: null,
      saldo: null,
      saldoFormatado: 'R$0.00',
      supervisor: '1',
      travas: false,
      usuario: '06092020',
    },
    driverAllPlatesAllGasLocked: {
      arla: true,
      centroCusto: '1',
      codigo: '24419482',
      cpf: '',
      dieselS10: true,
      dieselS500: true,
      etanol: true,
      gas: false,
      gasolina: true,
      gasolinaAditivada: true,
      limiteGastoAbastecimento: null,
      limiteGastoAbastecimentoFormatado: 'R$0.00',
      limiteGastoDiario: null,
      limiteGastoDiarioFormatado: 'R$0.00',
      limiteGastoMensal: null,
      limiteGastoMensalFormatado: 'R$0.00',
      matricula: '4',
      nome: 'fulano',
      origem: 'interno',
      perfil: 'motorista',
      permitePrecoDivergente: false,
      plate: null,
      plate_id: null,
      saldo: null,
      saldoFormatado: 'R$0.00',
      supervisor: '1',
      travas: true,
      usuario: '06092020',
    },
    valetAllPlatesAllGasUnlocked: {
      arla: true,
      centroCusto: '1',
      codigo: '24419482',
      cpf: '',
      dieselS10: true,
      dieselS500: true,
      etanol: true,
      gas: false,
      gasolina: true,
      gasolinaAditivada: true,
      limiteGastoAbastecimento: null,
      limiteGastoAbastecimentoFormatado: 'R$0.00',
      limiteGastoDiario: null,
      limiteGastoDiarioFormatado: 'R$0.00',
      limiteGastoMensal: null,
      limiteGastoMensalFormatado: 'R$0.00',
      matricula: '4',
      nome: 'fulano',
      origem: 'interno',
      perfil: 'manobrista',
      permitePrecoDivergente: false,
      plate: null,
      plate_id: null,
      saldo: null,
      saldoFormatado: 'R$0.00',
      supervisor: '1',
      travas: false,
      usuario: '06092020',
    },
    valetAllPlatesAllGasLocked: {
      arla: true,
      centroCusto: '1',
      codigo: '24419482',
      cpf: '',
      dieselS10: true,
      dieselS500: true,
      etanol: true,
      gas: false,
      gasolina: true,
      gasolinaAditivada: true,
      limiteGastoAbastecimento: null,
      limiteGastoAbastecimentoFormatado: 'R$0.00',
      limiteGastoDiario: null,
      limiteGastoDiarioFormatado: 'R$0.00',
      limiteGastoMensal: null,
      limiteGastoMensalFormatado: 'R$0.00',
      matricula: '4',
      nome: 'fulano',
      origem: 'interno',
      perfil: 'manobrista',
      permitePrecoDivergente: false,
      plate: null,
      plate_id: null,
      saldo: null,
      saldoFormatado: 'R$0.00',
      supervisor: '1',
      travas: true,
      usuario: '06092020',
    },
  },

};
